services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client:local

  downloader:
    build: ./server/database/downloader
    image: downloader:local

  db:
    build: ./server/database
    image: db:local

  api-gateway:
    build:
      context: ./server
      dockerfile: api-gateway/Dockerfile
    image: api-gateway:local

  stream-service:
    build:
      context: ./server
      dockerfile: StreamService/Dockerfile
    image: stream-service:local

  playlist-service:
    build:
      context: ./server
      dockerfile: PlaylistService/Dockerfile
    image: playlist-service:local

  genai-service:
    build:
      context: ./genai
      dockerfile: Dockerfile
    image: genai-service:local

  announcement-service:
    build:
      context: ./server
      dockerfile: AnnouncementService/Dockerfile
    image: announcement-service:local

  prometheus:
    build: ./monitoring/prometheus
    image: prometheus:local
