services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: aifm/client:local
    ports:
      - 8080:80

  downloader:
    build: ./server/database/downloader
    image: aifm/downloader:local

  db:
    build: ./server/database
    image: aifm/db:local

  api-gateway:
    build:
      context: ./server
      dockerfile: api-gateway/Dockerfile
    image: aifm/api-gateway:local
    ports:
      - 8090:8080

  stream-service:
    build:
      context: ./server
      dockerfile: StreamService/Dockerfile
    image: aifm/stream-service:local
    ports:
      - 8091:8080

  playlist-service:
    build:
      context: ./server
      dockerfile: PlaylistService/Dockerfile
    image: aifm/playlist-service:local
    ports:
      - 8092:8080

  genai-service:
    build:
      context: ./genai
      dockerfile: Dockerfile
    image: aifm/genai-service:local
    ports:
      - 8000:8000

  announcement-service:
    build:
      context: ./server
      dockerfile: AnnouncementService/Dockerfile
    image: aifm/announcement-service:local
    ports:
      - 8093:8080

  prometheus:
    build: ./monitoring/prometheus
    image: aifm/prometheus:local
    ports:
      - 9090:9090

  grafana:
    ports:
      - 3000:3000
