apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    io.kompose.service: api-gateway
spec:
  selector:
    io.kompose.service: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
