apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: audio-files
  name: audio-files
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
