apiVersion: v1
kind: Service
metadata:
  name: genai-service
  labels:
    app: genai-service  # <- Optional, but useful for grouping
spec:
  selector:
    app: genai-service  # <- Required for routing
  ports:
    - port: 8000
      targetPort: 8000
