apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: grafana-provisioning
  name: grafana-provisioning
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
