apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    app: grafana
  name: grafana
  namespace: aifm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../compose.yml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        app: grafana
    spec:
      containers:
        - env:
            - name: GF_LOG_LEVEL
              value: warn
            - name: GF_USERS_DEFAULT_THEME
              value: light
            - name: GF_SERVER_ROOT_URL
              value: https://aifm.student.k8s.aet.cit.tum.de/grafana/
          image: ghcr.io/aet-devops25/aifm/grafana:latest
          imagePullPolicy: Always
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
