apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: aifm
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Basic auth configuration
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "basic-auth"  # You must create this secret
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  tls:
    - hosts:
        - aifm.student.k8s.aet.cit.tum.de
      secretName: aifm-tls  # cert-manager will create and manage this
  rules:
    - host: aifm.student.k8s.aet.cit.tum.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: 80
