apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-data
  name: mysql-data
  namespace: aifm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
