apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    io.kompose.service: prometheus
spec:
  selector:
    io.kompose.service: prometheus
  ports:
    - port: 9090
      targetPort: 9090
