apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus-data
  name: prometheus-data
  namespace: aifm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
