apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sql-files
  name: sql-files
  namespace: aifm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
