version: '3.8'

services:
  streamservice:
    build:
      context: .
      dockerfile: StreamService/Dockerfile
    image: server-streamservice:latest
    ports:
      - "8080:8080"

  playlistservice:
    build:
      context: .
      dockerfile: PlaylistService/Dockerfile
    image: server-playlistservice
    ports:
      - "8081:8080"

  announcementservice:
    build:
      context: .
      dockerfile: AnnouncementService/Dockerfile
    image: server-announcementservice
    ports:
      - "8082:8080"
