server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: deny-actuator
          uri: http://localhost
          predicates:
            - Path=/api/*/actuator/**
          filters:
            - SetStatus=403

        - id: streamservice
          uri: http://stream-service:8080
          predicates:
            - Path=/api/stream/**
          filters:
            - RewritePath=/api/stream/(?<segment>.*), /${segment}
        - id: stream-docs
          uri: http://stream-service:8080
          predicates:
            - Path=/api/stream/v3/api-docs
          filters:
            - RewritePath=/api/stream/v3/api-docs, /v3/api-docs

        - id: playlistservice
          uri: http://playlist-service:8080
          predicates:
            - Path=/api/playlist/**
          filters:
            - RewritePath=/api/playlist/(?<segment>.*), /${segment}
        - id: playlist-docs
          uri: http://playlist-service:8080
          predicates:
            - Path=/api/playlist/v3/api-docs
          filters:
            - RewritePath=/api/playlist/v3/api-docs, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: streamservice
        url: /api/stream/v3/api-docs
      - name: playlistservice
        url: /api/playlist/v3/api-docs
  api-docs:
    enabled: true
