{
 "title": "DevOps - In the midst of chaos there is also opportunity",
 "time": { "from": "2025-06-26T19:16:12.775Z", "to": "2025-06-26T19:17:53.454Z" },
 "panels": [
  {
   "title": "Total request count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job) (http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (http_requests_total{handler!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(http_server_requests_seconds_sum{uri!=\"/actuator/prometheus\"}[5m])) / sum by(job) (rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (rate(http_request_duration_seconds_sum{handler!=\"/metrics\"}[5m])) / sum by(job) (rate(http_request_duration_seconds_count{handler!=\"/metrics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_requests_seconds_count{status=~\"4..\"}[1m])) / sum by (job) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "sum by (job) (rate(http_requests_total{status=~\"4..|5..\"}[1m])) / sum by (job) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}