global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'stream-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['streamservice:8080']

  - job_name: 'playlist-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['playlistservice:8080']

  - job_name: 'genai-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['genai_service:8000']