global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'stream-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['stream-service:8080']

  - job_name: 'playlist-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['playlist-service:8080']

  - job_name: 'genai-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['genai-service:8000']