name: GenAI Service CI

on:
  push:
    branches:
      - main
      - feature/new-ci
    paths:
      - 'genai/**'
  pull_request:
    paths:
      - 'genai/**'

jobs:
  test_and_build:
    name: Test and Build GenAI Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r genai/requirements.txt

      - name: Run Unit and Integration Tests with Pytest
        working-directory: ./genai
        run: pytest

      - name: Build Docker Compose services
        working-directory: ./genai
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: docker-compose up -d --build

      - name: Wait for services to be healthy
        run: sleep 10 # Simple wait for the service to start

      - name: Run Component Test (API test)
        working-directory: ./genai
        run: python tests/test_api.py

      - name: Stop services
        if: always() # Always run this step to clean up
        working-directory: ./genai
        run: docker-compose down

      - name: Build Production Docker Image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker build -t genai-service:latest -f genai/Dockerfile ./genai