name: Main CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      repo_sanitized: ${{ steps.setvar.outputs.repo_sanitized }}
      timestamp: ${{ steps.setvar.outputs.timestamp }}
    steps:
      - name: Set shared metadata
        id: setvar
        run: |
          echo "repo_sanitized=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]' | tr -d '.')" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

  test-client:
    name: Test Client
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Run tests
        working-directory: ./client
        # run: npm test -- --watch=false --browsers=ChromeHeadless
        run: echo "npm test temporarily disabled"

  test-genai:
    name: Test GenAI Service
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r genai/requirements.txt

      - name: Run Unit and Integration Tests with Pytest
        working-directory: ./genai
        run: pytest --ignore=tests/test_api.py

      - name: Build Docker Compose services
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
          BASIC_AUTH_PASS: ${{ secrets.BASIC_AUTH_PASS }}
          BASIC_AUTH_URL: ${{ secrets.BASIC_AUTH_URL }}
        run: docker compose up -d --build genai-service

      - name: Show container logs
        if: always()
        run: docker compose logs genai-service

      - name: Wait for GenAI service to be healthy
        run: |
          for i in {1..45}; do
            if curl -s http://localhost:8000/health | grep -q '"status":"ok"'; then
              echo "GenAI service is up!"
              exit 0
            fi
            echo "Waiting for GenAI service... ($i/45)"
            sleep 2
          done
          echo "GenAI service did not start in time."
          docker compose logs genai-service
          exit 1

      - name: Run Component Test (API test)
        working-directory: ./genai
        run: python tests/test_api.py

      - name: Stop services
        if: always()
        run: docker compose down


  test-server:
    name: Test Server
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew
        working-directory: server

      - name: Build all microservices
        run: ./gradlew build --no-daemon
        working-directory: server

      - name: Run unit tests for all services
        run: ./gradlew test --no-daemon
        working-directory: server

  build:
    needs: [setup, test-client, test-server, test-genai]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [client, playlist-service]
    env:
      REMOTE_IMAGE: ghcr.io/${{ needs.setup.outputs.repo_sanitized }}/${{ matrix.image }}
      IMAGE_TIMESTAMP: ${{ needs.setup.outputs.timestamp }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build image
        run: docker compose build ${{ matrix.image }}

      - name: Determine remote image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REMOTE_IMAGE }}
          tags: |
            type=sha
            type=raw,value=${{ github.run_id }}-${{ github.run_attempt }}
            type=raw,value=${{ env.IMAGE_TIMESTAMP }}
            type=raw,value=latest

      - name: Create remote image tags
        run: |
          while IFS= read -r tag; do
            echo Creating tag $tag
            docker tag ${{ matrix.image }}:local $tag
          done <<< "${{ steps.meta.outputs.tags }}"

      - name: Store all remote image tags
        run: docker save ${{ env.REMOTE_IMAGE }} > /tmp/${{ matrix.image }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image }}
          path: /tmp/${{ matrix.image }}.tar


  push:
    runs-on: ubuntu-latest
    needs: [setup, build]
    strategy:
      matrix:
        image: [client, playlist-service]
    env:
      REMOTE_IMAGE: ghcr.io/${{ needs.setup.outputs.repo_sanitized }}/${{ matrix.image }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.image }}
          path: /tmp

      - name: Load all remote image tags
        run: |
          docker load < /tmp/${{ matrix.image }}.tar
          docker image ls -a

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push to registry
        run: docker push --all-tags ${{ env.REMOTE_IMAGE }}

      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v4
        with:
          name: ${{ matrix.image }}
