name: Main CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-build-client:
    if: |
      contains(github.event.pull_request.labels.*.name, 'client') ||
      (github.event_name == 'push' && (contains(join(github.event.commits.*.modified, ' '), 'client/') || contains(join(github.event.commits.*.added, ' '), 'client/')))
    name: Test and Build Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Using a recent LTS version

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Run tests
        working-directory: ./client
        # The --watch=false and --browsers=ChromeHeadless are crucial for CI environments
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Build the application
        working-directory: ./client
        run: npm run build

      - name: Build Production Docker Image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker build -t client:latest -f client/Dockerfile ./client

  test-and-build-genai:
    if: |
      contains(github.event.pull_request.labels.*.name, 'genai') ||
      (github.event_name == 'push' && (contains(join(github.event.commits.*.modified, ' '), 'genai/') || contains(join(github.event.commits.*.added, ' '), 'genai/')))
    name: Test and Build GenAI Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Install Python dependencies
        run: pip install -r genai/requirements.txt

      - name: Run Unit and Integration Tests with Pytest
        working-directory: ./genai
        run: pytest

      - name: Build Docker Compose services
        working-directory: ./genai
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: docker-compose up -d --build

      - name: Show container logs
        if: always()
        working-directory: ./genai
        run: docker-compose logs

      - name: Wait for GenAI service to be healthy
        run: |
          # Increased timeout to 90 seconds (45 attempts * 2 seconds)
          for i in {1..45}; do
            if curl -s http://localhost:8000/health | grep -q '"status":"ok"'; then
              echo "GenAI service is up!"
              exit 0
            fi
            echo "Waiting for GenAI service... ($i/45)"
            sleep 2
          done
          echo "GenAI service did not start in time."
          # Get logs again on failure
          docker-compose -f genai/docker-compose.yaml logs
          exit 1

      - name: Run Component Test (API test)
        working-directory: ./genai
        run: python tests/test_api.py

      - name: Stop services
        if: always() # Always run this step to clean up
        working-directory: ./genai
        run: docker-compose down

      - name: Build Production Docker Image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker build -t genai-service:latest -f genai/Dockerfile ./genai

  test-and-build-server:
    if: |
      contains(github.event.pull_request.labels.*.name, 'server') ||
      (github.event_name == 'push' && (contains(join(github.event.commits.*.modified, ' '), 'server/') || contains(join(github.event.commits.*.added, ' '), 'server/')))
    name: Build and Test Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew
        working-directory: server

      - name: Build all microservices
        run: ./gradlew build --no-daemon
        working-directory: server

      - name: Run unit tests for StreamService
        run: ./gradlew :StreamService:test --no-daemon
        working-directory: server

      - name: Run unit tests for PlaylistService
        run: ./gradlew :PlaylistService:test --no-daemon
        working-directory: server

      - name: Run unit tests for AnnouncementService
        run: ./gradlew :AnnouncementService:test --no-daemon
        working-directory: server