apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: stream-service
  name: stream-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: stream-service
